// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as channelsRouteImport } from "./routes/channels";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as agentsDotsetupRouteImport } from "./routes/agents.setup";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsRoute = channelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsDotsetupRoute = agentsDotsetupRouteImport.update({
  id: "/agents/setup",
  path: "/agents/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/channels": typeof channelsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/agents/setup": typeof agentsDotsetupRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/channels": typeof channelsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/agents/setup": typeof agentsDotsetupRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/channels": typeof channelsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/agents/setup": typeof agentsDotsetupRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/channels"
    | "/projects"
    | "/pulse"
    | "/repos"
    | "/settings"
    | "/workflows"
    | "/agents/setup"
    | "/invite/$code"
    | "/projects/$projectId"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/channels"
    | "/projects"
    | "/pulse"
    | "/repos"
    | "/settings"
    | "/workflows"
    | "/agents/setup"
    | "/invite/$code"
    | "/projects/$projectId"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/channels"
    | "/projects"
    | "/pulse"
    | "/repos"
    | "/settings"
    | "/workflows"
    | "/agents/setup"
    | "/invite/$code"
    | "/projects/$projectId"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  channelsRoute: typeof channelsRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  reposRoute: typeof reposRoute;
  settingsRoute: typeof settingsRoute;
  workflowsRoute: typeof workflowsRoute;
  agentsDotsetupRoute: typeof agentsDotsetupRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels": {
      id: "/channels";
      path: "/channels";
      fullPath: "/channels";
      preLoaderRoute: typeof channelsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents/setup": {
      id: "/agents/setup";
      path: "/agents/setup";
      fullPath: "/agents/setup";
      preLoaderRoute: typeof agentsDotsetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  channelsRoute: channelsRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  reposRoute: reposRoute,
  settingsRoute: settingsRoute,
  workflowsRoute: workflowsRoute,
  agentsDotsetupRoute: agentsDotsetupRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
